version: '3.8'

services:
  tanachat-app:
    build:
      context: ./app
      dockerfile: Dockerfile.do
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_CDN_URL=http://localhost:5173
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: unless-stopped
    networks:
      - tanachat-local

networks:
  tanachat-local:
    driver: bridge