version: '3.8'

services:
  tanachat-mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile.do
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=8000
      # Local development URLs
      - VITE_API_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./mcp/src:/app/src
      - ./mcp/pyproject.toml:/app/pyproject.toml
      - ./mcp/uv.lock:/app/uv.lock
    restart: unless-stopped
    networks:
      - tanachat-local

networks:
  tanachat-local:
    driver: bridge