github: thomashaus
patreon: # Replace with your Patreon username if applicable
open_collective: # Replace with your Open Collective name if applicable
ko_fi: # Replace with your Ko-fi username if applicable
tidelift: # Replace with your Tidelift package name if applicable
community_bridge: # Replace with your Community Bridge project name if applicable
liberapay: # Replace with your Liberapay username if applicable
issuehunt: # Replace with your IssueHunt username if applicable
otechie: # Replace with your Otechie username if applicable
custom: ['https://github.com/sponsors/thomashaus']