name: tanachat-mcp
services:
- name: mcp-server
  image:
    registry_type: DOCR
    registry: espresso
    repository: tanachat-mcp
    tag: latest
    deploy_on_push:
      enabled: false
  envs:
  - key: PYTHON_VERSION
    value: "3.12"
  - key: TANA_API_KEY
    type: SECRET
    value: ${tana-api-key}
  - key: S3_ACCESS_KEY
    type: SECRET
    value: ${s3-access-key}
  - key: S3_SECRET_KEY
    type: SECRET
    value: ${s3-secret-key}
  - key: S3_BUCKET
    value: tanachat
  - key: S3_REGION
    value: nyc3
  - key: S3_ENDPOINT
    value: https://nyc3.digitaloceanspaces.com
  - key: CORS_ORIGINS
    value: https://tanachat.ai,https://api.tanachat.ai,https://mcp.tanachat.ai
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
domains:
- domain: mcp.tanachat.ai
  type: PRIMARY
- domain: api.tanachat.ai
  type: ALIAS
region: nyc